---
volumes:
  acme: {}

services:
  router:
    image: traefik:v2.8
    restart: always
#    network_mode: 'host'
    command: traefik
      --api.dashboard=false

      --entryPoints.web.address=:80

      --entryPoints.websecure.address=:443
      --entryPoints.websecure.http.tls=true
      --entryPoints.websecure.http.tls.certresolver=myresolver


      --entryPoints.web.http.redirections.entryPoint.to=websecure
      --entryPoints.web.http.redirections.entryPoint.scheme=https
      --entryPoints.web.http.redirections.entrypoint.permanent=true

      --providers.docker=true
      --providers.docker.exposedByDefault=false
      --providers.docker.network=traefik-router

      --log.level=DEBUG
      --accessLog=true

      --certificatesResolvers.myresolver.acme.email=avarets1234@gmail.com
      --certificatesresolvers.myresolver.acme.storage=/etc/traefik/acme/acme.json
      --certificatesresolvers.myresolver.acme.httpchallenge=true
      --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web

      --api.dashboard=true
      --api.insecure=true

      --providers.http.endpoint=http://http_config_provider:9000
    volumes:
      - acme:/etc/traefik/acme
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "443:443"
#      - "8080:8080"
#    networks:
#     - default
#      - network1

networks:
  default:
    name: traefik-router
