---
services:
  library_db:
    container_name: db_chat
    image: postgres:12
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./var/pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
